### ISSUE TITLE
Remove deprecate endpoints

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_backend#44]
- [ ] Remove deprecate endpoints (`/hello`, `/whoami`)
- [ ] Remove corresponding event JSON files
- [ ] Update API documentation

**Comment by VictorAlagwu** [comment]
I will like to work on this @rubenhorn, anyone working on it yet ?

**Comment by rubenhorn** [comment]
Not yet.
Looking forward to your PR.
