### ISSUE TITLE
Re-implement app version validation in contact endpoint

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_backend#82]
RegEx: `^(?:ios|android) [0-9]+\\.[0-9]+\\.[0-9]+\\+[0-9]+$`
(see: https://github.com/CollActionteam/collaction_backend/blob/development/internal/models/contact.go#L8)

Also: Add line break between message and app version.

**Comment by mrsoftware** [comment]
this task is done before: https://github.com/CollActionteam/collaction_backend/blob/development/internal/models/contact.go#L36
Am I missing something?

**Comment by rubenhorn** [comment]
No, you are right. Closing.
